# Build the Next.js application
build:
	npm run build

# Start the Next.js application in production mode
serve:
	npm run start

start:
	npm run dev

# Define a simple stop command if you're using pm2 or similar
stop:
	pm2 stop all

killport:
	killport 3000

